### PR TITLE
Fixed a lot things in business

### LINKED ISSUE #93: Porter need to move around

### LINKED ISSUE #94: Porter interact with you when you are in a locked room #BadGuy

### LINKED ISSUE #95: Map generation needs to create a room that is locked

### PR DESCRIPTION
**Pull request by frederikrosenberg**
- Fixed #95 / #75 
- Fixed #94 
- Fixed #93 
- Added interact to IBusiness
- Added a game state to business
- Inventory checks if there is space

### CODE REVIEW

**Review by larsbjn — APPROVED** [review]

File: HospitalGame_Business/src/business/Item/ItemFacade.java [hunk 1]
```diff
@@ -47,8 +47,10 @@ public int createInventory(int maxWeight) {
     public boolean addItem(int inventoryID, IItem item) {
         for (Inventory inventory : inventoryList) {
             if (inventory.getInventoryID() == inventoryID) {
-                inventory.addItem(item);
-                return true;
+                if (inventory.getMaxWeight() >= inventory.getTotalWeight() + item.getWeight()) {
```
Comment (AndreasBoegh) [inline HospitalGame_Business/src/business/Item/ItemFacade.java]: Already checks maxWeight in inventory class

Comment (AndreasBoegh) [inline HospitalGame_Business/src/business/Item/ItemFacade.java]: request changes instead

**Review by AndreasBoegh — CHANGES_REQUESTED** [review]

**Review by AndreasBoegh — APPROVED** [review]
